apiVersion: apps/v1
kind: Deployment
metadata:
  name: youcefs-juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcefs-juice-shop
  template:
    metadata:
      labels:
        app: youcefs-juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: youcefs-juice-shop
spec:
  selector:
    app: youcefs-juice-shop
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juice-shop-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.74/32"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: youcefs-juice-shop
            port:
              number: 3000
