apiVersion: apps/v1
kind: Deployment
metadata:
  name: youcefs-juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcefs-juice-shop
  template:
    metadata:
      labels:
        app: youcefs-juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop:latest
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: youcefs-juice-shop
spec:
  selector:
    app: youcefs-juice-shop
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP